# Generated by Django 6.0.4 on 2026-04-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_description_product_category_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FEAT', 'Featured'), ('PR', 'Premium'), ('LIM', 'Limited'), ('VEG', 'Vegan')], default='FEAT', max_length=4),
        ),
    ]
