# Generated by Django 6.0.4 on 2026-04-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Featured', 'Featured'), ('Premium', 'Premium'), ('Limited', 'Limited'), ('Vegan', 'Vegan')], default='Featured', max_length=20),
        ),
    ]
