# Generated by Django 6.0.4 on 2026-05-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='orderProduct',
            field=models.ManyToManyField(related_name='orders', to='store.cartitem'),
        ),
    ]
